[package]
name = "youmuz"
edition = "2024"
version = "0.1.0"

[lib]
name = "youmuz"
crate-type = ["cdylib", "staticlib"]

[dependencies]

mimalloc = { version = "0.1.52" }

# Core 
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "fs"] }
reqwest = { version = "0.13.4", default-features = false, features = [
  "rustls",
  "brotli",
  "json",
  "http2",
  "multipart",
  "query",
] }

# Audio
symphonia = { version = "0.5.5", default-features = false}
rodio = { version = "0.22.2", default-features = false, features = [
  "playback",
  "symphonia-flac",
  "symphonia-aac",
  "symphonia-mp3",
  "symphonia-isomp4",
  "symphonia-simd",
  "tracing",
  "crossbeam-channel",
] }

yandex-music = "0.7.0"
chrono = { version = "0.4.45", features = ["serde"] }
flutter_rust_bridge = { version = "=2.13.0" }
serde = { version = "1.0.229", features = ["derive"] }

# Logging
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
directories = "6.0.0"

# Utilities
flume = "0.12.0"
rand = "0.10.2"
crossbeam-channel = "0.5.16"
thiserror = "2.0.20"
futures = "0.3.34"
serde_json = "1.0.151"

im = "15.1.0"
arc-swap = "1.9.2"
rusqlite = { version = "0.40", features = ["bundled"] }


parking_lot = "0.12.5"
foldhash = "0.2.0"
urlencoding = "2.1.3"
lofty = "0.25.1"
bytes = "1.12.1"
regex = "1.13.1"
quick-xml = "0.41.0"
[target.'cfg(not(target_os = "android"))'.dependencies]
discord-rich-presence = "1.1.0"
wayclip-global-hotkey = "0.7"
souvlaki = { git = "https://github.com/Sinono3/souvlaki", rev = "93ff3d1" }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
    "Win32_UI_Controls",
    "Win32_System_Com",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Gdi",
    "Win32_System_Threading",
    "Win32_System_LibraryLoader",
    "Win32_Graphics_Imaging",
    "Win32_Media_Audio",
] }

[target.'cfg(target_os = "android")'.dependencies]
rustls-platform-verifier = { version = "0.7.0", features = ["jni"] }
jni = "0.22"
ndk-context = "0.1.1"
mimalloc = { workspace = true, features = ["local_dynamic_tls"] }

[workspace]
members = ["."]

[workspace.dependencies]
mimalloc = { version = "0.1.52" }


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
debug = false
debug-assertions = false
strip = "symbols"
