pub mod cache;
pub mod commands;
pub mod controller;
#[cfg(not(any(target_os = "android")))]
pub mod discord;
pub mod enums;
pub mod fetcher;
pub mod fx;
pub mod history;
pub mod liked;
pub mod monitor;
pub mod playback;
pub mod prefetcher;
pub mod progress;
pub mod queue;
pub mod shuffle;
pub mod signals;
#[cfg(not(any(target_os = "android")))]
pub mod smtc;
pub mod state;
pub mod stream_manager;
pub mod system;
#[cfg(target_os = "windows")]
pub mod taskbar;
#[cfg(target_os = "windows")]
pub mod thumbnail;
pub mod util;
pub mod vibe;
pub mod yandex;
